# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1

_defaults: &defaults
    docker:
      - image: circleci/golang:1.11

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: go-mod-v3-{{ checksum "go.sum" }}
      - run:
          name: Building and testing
          command: |
            go build ./...
            go get -u github.com/onsi/ginkgo/ginkgo
            go get -u github.com/onsi/gomega/...
            go get -u github.com/loongy/covermerge
            go get -u github.com/mattn/goveralls
            CI=true /go/bin/ginkgo -v --race --cover --coverprofile coverprofile.out ./...
            /go/bin/covermerge          \
              badgerdb/coverprofile.out \
              cache/coverprofile.out    \
              memdb/coverprofile.out > coverprofile.out
            /go/bin/goveralls -coverprofile=coverprofile.out -service=circleci -repotoken $COVERALLS_REPO_TOKEN
      - save_cache:
          key: go-mod-v3-{{ checksum "go.sum" }}
          paths:
            - "~/go"

workflows:
  version: 2.1
  build:
    jobs:
    - build
